import React from 'react';
export default function PrivacyPolicy() {
  return (
    <div className="container mx-auto px-4 py-8 flex">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      
      <p className="mb-4">
        This privacy policy applies to the Where is Kaaba app (hereby referred to as &ldquo;pplication&ldquo;) 
        for mobile devices that was created by JiSaNoAi (hereby referred to as &ldquo;Service Provider&ldquo;) 
        as a Free service. This service is intended for use &ldquo;AS IS&ldquo;.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Information Collection and Use</h2>
      <p className="mb-4">
        The Application collects information when you download and use it. This information may include:
      </p>
      <ul className="list-disc pl-8 mb-4">
        <li>Your device&apos;s Internet Protocol address (e.g. IP address)</li>
        <li>The pages of the Application that you visit, the time and date of your visit, the time spent on those pages</li>
        <li>The time spent on the Application</li>
        <li>The operating system you use on your mobile device</li>
      </ul>

      <p className="mb-4">
        The Application does not gather precise information about the location of your mobile device.
      </p>

      <p className="mb-4">
        The Application collects your device&apos;s location, which helps the Service Provider determine 
        your approximate geographical location and make use of in the following ways:
      </p>
      <ul className="list-disc pl-8 mb-4">
        <li>Geolocation Services: The Service Provider utilizes location data to provide features such as personalized content, relevant recommendations, and location-based services.</li>
        <li>Analytics and Improvements: Aggregated and anonymized location data helps the Service Provider to analyze user behavior, identify trends, and improve the overall performance and functionality of the Application.</li>
        <li>Third-Party Services: Periodically, the Service Provider may transmit anonymized location data to external services. These services assist them in enhancing the Application and optimizing their offerings.</li>
      </ul>

      {/* Add more sections here */}

      <h2 className="text-2xl font-semibold mt-6 mb-4">Contact Us</h2>
      <p className="mb-4">
        If you have any questions regarding privacy while using the Application, or have questions 
        about the practices, please contact the Service Provider via email at jisanoai@gmail.com.
      </p>

      <hr className="my-8" />

      <p className="text-sm text-gray-600">
        This privacy policy page was generated by{' '}
        <a href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
          App Privacy Policy Generator
        </a>
      </p>
    </div>
  );
};
